/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CarbonNeutralRouteImport } from './routes/carbon-neutral'
import { Route as ConservationRouteImport } from './routes/conservation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TreksRouteImport } from './routes/treks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CarbonNeutralRoute = CarbonNeutralRouteImport.update({
  id: '/carbon-neutral',
  path: '/carbon-neutral',
  getParentRoute: () => rootRouteImport,
} as any)
const ConservationRoute = ConservationRouteImport.update({
  id: '/conservation',
  path: '/conservation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TreksRoute = TreksRouteImport.update({
  id: '/treks',
  path: '/treks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/carbon-neutral': typeof CarbonNeutralRoute
  '/conservation': typeof ConservationRoute
  '/contact': typeof ContactRoute
  '/team': typeof TeamRoute
  '/treks': typeof TreksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/carbon-neutral': typeof CarbonNeutralRoute
  '/conservation': typeof ConservationRoute
  '/contact': typeof ContactRoute
  '/team': typeof TeamRoute
  '/treks': typeof TreksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/carbon-neutral': typeof CarbonNeutralRoute
  '/conservation': typeof ConservationRoute
  '/contact': typeof ContactRoute
  '/team': typeof TeamRoute
  '/treks': typeof TreksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/carbon-neutral'
    | '/conservation'
    | '/contact'
    | '/team'
    | '/treks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/carbon-neutral'
    | '/conservation'
    | '/contact'
    | '/team'
    | '/treks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/carbon-neutral'
    | '/conservation'
    | '/contact'
    | '/team'
    | '/treks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CarbonNeutralRoute: typeof CarbonNeutralRoute
  ConservationRoute: typeof ConservationRoute
  ContactRoute: typeof ContactRoute
  TeamRoute: typeof TeamRoute
  TreksRoute: typeof TreksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carbon-neutral': {
      id: '/carbon-neutral'
      path: '/carbon-neutral'
      fullPath: '/carbon-neutral'
      preLoaderRoute: typeof CarbonNeutralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conservation': {
      id: '/conservation'
      path: '/conservation'
      fullPath: '/conservation'
      preLoaderRoute: typeof ConservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treks': {
      id: '/treks'
      path: '/treks'
      fullPath: '/treks'
      preLoaderRoute: typeof TreksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CarbonNeutralRoute: CarbonNeutralRoute,
  ConservationRoute: ConservationRoute,
  ContactRoute: ContactRoute,
  TeamRoute: TeamRoute,
  TreksRoute: TreksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
